version: '3.8'
name: my-mastermind

services:
  app:
    container_name: game
    build: .
    volumes:
      - ./src/data:/usr/src/app/src/data
    ports:
      - "4000:4000"
    stdin_open: true # Hold the stdin open
    tty: true # Allocates a pseudo-TTY
    environment:
      - DB_FILE=/usr/src/app/src/data/MM_Reach.db


