version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./data:/usr/src/app/data
    ports:
      - "4000:4000"
    stdin_open: true # Hold the stdin open
    tty: true # Allocates a pseudo-TTY
    environment:
      - DB_FILE=/usr/src/app/data/MM_Reach.db


# Need to add jar files